Repository Beyond-B/Beyond-B-Back, pull requests merged in 2024-02, with the labels that each got.

#9 ✨ [Feat]: 엔티티 설계
  src/main/java/com/beyondB/beyondB/entity/Book.java
  src/main/java/com/beyondB/beyondB/entity/BookAge.java
  src/main/java/com/beyondB/beyondB/entity/BookQuiz.java
  src/main/java/com/beyondB/beyondB/entity/Diary.java
  src/main/java/com/beyondB/beyondB/entity/Feeling.java
  src/main/java/com/beyondB/beyondB/entity/User.java
  src/main/java/com/beyondB/beyondB/entity/common/BaseEntity.java
  src/main/java/com/beyondB/beyondB/entity/enums/Age.java
  src/main/java/com/beyondB/beyondB/entity/enums/Emotion.java
  src/main/java/com/beyondB/beyondB/entity/mapping/BookFeeling.java
  src/main/java/com/beyondB/beyondB/entity/mapping/DiaryFeeling.java
  src/main/java/com/beyondB/beyondB/entity/mapping/UserBook.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#11 :recycle: [Refactor]: 엔티티 수정
  src/main/java/com/beyondB/beyondB/entity/BookAge.java
  src/main/java/com/beyondB/beyondB/entity/Feeling.java
  src/main/resources/application.yml
Labels: :recycle: refactor

#14 :sparkles: [Feat]: API 응답 통일
  build.gradle
  src/main/java/com/beyondB/beyondB/apiPayload/BaseResponse.java
  src/main/java/com/beyondB/beyondB/apiPayload/code/BaseCode.java
  src/main/java/com/beyondB/beyondB/apiPayload/code/BaseErrorCode.java
  src/main/java/com/beyondB/beyondB/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/beyondB/beyondB/apiPayload/code/ReasonDTO.java
  src/main/java/com/beyondB/beyondB/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/beyondB/beyondB/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/beyondB/beyondB/apiPayload/exception/AuthException.java
  src/main/java/com/beyondB/beyondB/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/beyondB/beyondB/apiPayload/exception/GeneralException.java
  src/main/java/com/beyondB/beyondB/apiPayload/exception/RecreationException.java
  src/main/java/com/beyondB/beyondB/apiPayload/exception/RecreationReviewException.java
  src/main/java/com/beyondB/beyondB/apiPayload/exception/S3Exception.java
  src/main/java/com/beyondB/beyondB/apiPayload/exception/UserException.java
  src/main/java/com/beyondB/beyondB/entity/User.java
  src/main/java/com/beyondB/beyondB/entity/enums/Role.java
  src/main/java/com/beyondB/beyondB/repository/UserRepository.java
  src/main/java/com/beyondB/beyondB/service/UserService.java
  src/main/java/com/beyondB/beyondB/service/impl/UserServiceImpl.java
Labels: :sparkles: feature

#15 :sparkles: [Feat]: 소셜 로그인 구현 (카카오, 네이버, 구글)
  .github/workflows/dev_deploy.yml
  build.gradle
  src/main/java/com/beyondB/beyondB/config/SwaggerConfig.java
  src/main/java/com/beyondB/beyondB/controller/UserController.java
  src/main/java/com/beyondB/beyondB/dto/UserSignupDTO.java
  src/main/java/com/beyondB/beyondB/entity/User.java
  src/main/java/com/beyondB/beyondB/entity/enums/Role.java
  src/main/java/com/beyondB/beyondB/entity/enums/SocialType.java
  src/main/java/com/beyondB/beyondB/repository/UserRepository.java
  src/main/java/com/beyondB/beyondB/security/CustomOAuth2User.java
  src/main/java/com/beyondB/beyondB/security/OAuthAttributes.java
  src/main/java/com/beyondB/beyondB/security/config/SecurityConfig.java
  src/main/java/com/beyondB/beyondB/security/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/beyondB/beyondB/security/jwt/service/JwtService.java
  src/main/java/com/beyondB/beyondB/security/jwt/util/PasswordUtil.java
  src/main/java/com/beyondB/beyondB/security/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/beyondB/beyondB/security/login/handler/LoginFailureHandler.java
  src/main/java/com/beyondB/beyondB/security/login/handler/LoginSuccessHandler.java
  src/main/java/com/beyondB/beyondB/security/login/service/LoginService.java
  src/main/java/com/beyondB/beyondB/security/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/beyondB/beyondB/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/beyondB/beyondB/security/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/beyondB/beyondB/security/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/com/beyondB/beyondB/security/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/com/beyondB/beyondB/security/oauth2/userinfo/NaverOAuth2UserInfo.java
  src/main/java/com/beyondB/beyondB/security/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/com/beyondB/beyondB/security/test/TestAuthController.java
  src/main/java/com/beyondB/beyondB/security/test/TestAuthService.java
  src/main/java/com/beyondB/beyondB/security/test/dto/LoginRequest.java
  src/main/java/com/beyondB/beyondB/security/test/dto/LoginResponse.java
  src/main/java/com/beyondB/beyondB/service/UserService.java
  src/main/java/com/beyondB/beyondB/service/impl/UserServiceImpl.java
  src/main/resources/application-jwt.yml
  src/main/resources/application-oauth-dev.yml
  src/main/resources/application-oauth-local.yml
  src/main/resources/application.yml
  src/main/resources/static/index.html
  src/test/java/com/beyondB/beyondB/BeyondBApplicationTests.java
Labels: :sparkles: feature

#17 ✨ [Feat]: 일기 수정 API
  src/main/java/com/beyondB/beyondB/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/beyondB/beyondB/apiPayload/exception/DiaryException.java
  src/main/java/com/beyondB/beyondB/config/WebConfig.java
  src/main/java/com/beyondB/beyondB/controller/DiaryController.java
  src/main/java/com/beyondB/beyondB/converter/DiaryConverter.java
  src/main/java/com/beyondB/beyondB/dto/request/DiaryRequestDTO.java
  src/main/java/com/beyondB/beyondB/dto/response/DiaryResponseDTO.java
  src/main/java/com/beyondB/beyondB/entity/Diary.java
  src/main/java/com/beyondB/beyondB/repository/DiaryRepository.java
  src/main/java/com/beyondB/beyondB/service/DiaryService.java
  src/main/java/com/beyondB/beyondB/service/impl/DiaryServiceImpl.java
Labels: :sparkles: feature

#23 🚑 [HOTFIX]: 엔티티 중복 수정
  src/main/java/com/beyondB/beyondB/entity/Diary.java
Labels: :bug: bug

#25 🚑 [HOTFIX]: 한글문제가 아니라 엔티티 설계 문제 해결
  src/main/java/com/beyondB/beyondB/dto/request/DiaryRequestDTO.java
  src/main/java/com/beyondB/beyondB/entity/Book.java
  src/main/java/com/beyondB/beyondB/entity/Diary.java
  src/main/java/com/beyondB/beyondB/entity/Feeling.java
  src/main/java/com/beyondB/beyondB/entity/mapping/BookFeeling.java
  src/main/java/com/beyondB/beyondB/entity/mapping/DiaryFeeling.java
  src/main/java/com/beyondB/beyondB/repository/DiaryFeelingRepository.java
  src/main/java/com/beyondB/beyondB/service/impl/DiaryServiceImpl.java
Labels: :bug: bug

#30 ✨ [Feat]: 한 달간 일기 조회 API
  src/main/java/com/beyondB/beyondB/controller/DiaryController.java
  src/main/java/com/beyondB/beyondB/converter/DiaryConverter.java
  src/main/java/com/beyondB/beyondB/dto/request/DiaryRequestDTO.java
  src/main/java/com/beyondB/beyondB/dto/response/DiaryResponseDTO.java
  src/main/java/com/beyondB/beyondB/repository/DiaryRepository.java
  src/main/java/com/beyondB/beyondB/service/DiaryService.java
  src/main/java/com/beyondB/beyondB/service/impl/DiaryServiceImpl.java
Labels: :sparkles: feature

#34 ✨ [Feat]: 책 등록 API
  src/main/java/com/beyondB/beyondB/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/beyondB/beyondB/apiPayload/exception/BookException.java
  src/main/java/com/beyondB/beyondB/controller/bookController.java
  src/main/java/com/beyondB/beyondB/converter/BookConverter.java
  src/main/java/com/beyondB/beyondB/dto/request/BookRequestDTO.java
  src/main/java/com/beyondB/beyondB/dto/response/BookResponseDTO.java
  src/main/java/com/beyondB/beyondB/entity/Book.java
  src/main/java/com/beyondB/beyondB/entity/BookAge.java
  src/main/java/com/beyondB/beyondB/entity/enums/Age.java
  src/main/java/com/beyondB/beyondB/repository/BookAgeRepository.java
  src/main/java/com/beyondB/beyondB/repository/BookRepository.java
  src/main/java/com/beyondB/beyondB/service/BookService.java
  src/main/java/com/beyondB/beyondB/service/impl/BookServiceImpl.java
Labels: :sparkles: feature

#33 ✨ [Feat]: 기분별 책 조회 API
  src/main/java/com/beyondB/beyondB/controller/BookController.java
  src/main/java/com/beyondB/beyondB/converter/BookConverter.java
  src/main/java/com/beyondB/beyondB/dto/response/BookResponseDTO.java
  src/main/java/com/beyondB/beyondB/entity/Book.java
  src/main/java/com/beyondB/beyondB/repository/BookRepository.java
  src/main/java/com/beyondB/beyondB/repository/UserBookRepository.java
  src/main/java/com/beyondB/beyondB/security/SecurityConfig.java
  src/main/java/com/beyondB/beyondB/service/BookService.java
  src/main/java/com/beyondB/beyondB/service/impl/BookServiceImpl.java
Labels: :sparkles: feature

#37 ♻️ [Refactor]: 로그인 및 회원가입 요구사항대로 수정
  src/main/java/com/beyondB/beyondB/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/beyondB/beyondB/controller/AuthController.java
  src/main/java/com/beyondB/beyondB/dto/UserSignupDTO.java
  src/main/java/com/beyondB/beyondB/dto/request/LoginRequestDTO.java
  src/main/java/com/beyondB/beyondB/entity/User.java
  src/main/java/com/beyondB/beyondB/repository/UserRepository.java
  src/main/java/com/beyondB/beyondB/security/SecurityConfig.java
  src/main/java/com/beyondB/beyondB/service/AuthService.java
  src/main/java/com/beyondB/beyondB/service/impl/AuthServiceImpl.java
  src/main/java/com/beyondB/beyondB/service/impl/UserServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#38 ✨ [Feat]: 책 상세 조회 API
  src/main/java/com/beyondB/beyondB/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/beyondB/beyondB/apiPayload/exception/UserBookException.java
  src/main/java/com/beyondB/beyondB/controller/BookController.java
  src/main/java/com/beyondB/beyondB/converter/BookConverter.java
  src/main/java/com/beyondB/beyondB/dto/request/BookRequestDTO.java
  src/main/java/com/beyondB/beyondB/dto/response/BookResponseDTO.java
  src/main/java/com/beyondB/beyondB/repository/UserBookRepository.java
  src/main/java/com/beyondB/beyondB/service/BookService.java
  src/main/java/com/beyondB/beyondB/service/impl/BookServiceImpl.java
Labels: :sparkles: feature

#41 ✨ [Feat]: 책 퀴즈 요청 API
  src/main/java/com/beyondB/beyondB/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/beyondB/beyondB/apiPayload/exception/BookQuizException.java
  src/main/java/com/beyondB/beyondB/apiPayload/exception/UserBookException.java
  src/main/java/com/beyondB/beyondB/controller/QuizController.java
  src/main/java/com/beyondB/beyondB/controller/bookController.java
  src/main/java/com/beyondB/beyondB/converter/QuizConverter.java
  src/main/java/com/beyondB/beyondB/dto/response/QuizResponseDTO.java
  src/main/java/com/beyondB/beyondB/entity/BookQuiz.java
  src/main/java/com/beyondB/beyondB/repository/UserBookRepository.java
  src/main/java/com/beyondB/beyondB/service/QuizService.java
  src/main/java/com/beyondB/beyondB/service/impl/QuizServiceImpl.java
Labels: :sparkles: feature

#45 🚑 [HOTFIX]: 빌드 문제 해결
  src/main/java/com/beyondB/beyondB/controller/bookController.java
Labels: :bug: bug

#46 ✨ [Feat]: 가장 최근에 푼 퀴즈의 책 ID 반환 API
  src/main/java/com/beyondB/beyondB/controller/BookController.java
  src/main/java/com/beyondB/beyondB/converter/BookConverter.java
  src/main/java/com/beyondB/beyondB/dto/response/BookResponseDTO.java
  src/main/java/com/beyondB/beyondB/service/BookService.java
  src/main/java/com/beyondB/beyondB/service/impl/BookServiceImpl.java
Labels: :sparkles: feature

#51 ✨ [Feat]: 마이페이지 조회
  src/main/java/com/beyondB/beyondB/controller/UserController.java
  src/main/java/com/beyondB/beyondB/converter/UserConverter.java
  src/main/java/com/beyondB/beyondB/dto/response/UserResponseDTO.java
  src/main/java/com/beyondB/beyondB/entity/enums/Emotion.java
Labels: :sparkles: feature

#54 ♻️ [Refactor]: 책 추천 할때 나이를 나이 분류로 변환하게 변경
  src/main/java/com/beyondB/beyondB/controller/BookController.java
  src/main/java/com/beyondB/beyondB/service/BookService.java
  src/main/java/com/beyondB/beyondB/service/impl/BookServiceImpl.java
  src/main/java/com/beyondB/beyondB/service/impl/UserServiceImpl.java
Labels: :recycle: refactor

#57 ♻️ [Refactor]: 일기 등록 수정
  src/main/java/com/beyondB/beyondB/converter/DiaryConverter.java
  src/main/java/com/beyondB/beyondB/service/impl/DiaryServiceImpl.java
Labels: :recycle: refactor

#59 :recycle: [Refactor]: 책 추천 API 수정
  src/main/java/com/beyondB/beyondB/service/impl/BookServiceImpl.java
Labels: :recycle: refactor

#61 ♻️ [Refactor]: 감정별 책 조회시, 추천 받은 책들만 조회할 수 있게 변경
  src/main/java/com/beyondB/beyondB/controller/BookController.java
  src/main/java/com/beyondB/beyondB/converter/BookConverter.java
  src/main/java/com/beyondB/beyondB/repository/UserBookRepository.java
  src/main/java/com/beyondB/beyondB/service/BookService.java
  src/main/java/com/beyondB/beyondB/service/impl/BookServiceImpl.java
Labels: :recycle: refactor

#63 ♻️ [Refactor]: 책을 추천할때 실제 나이보다 어린 책을 추천
  src/main/java/com/beyondB/beyondB/service/impl/BookServiceImpl.java
Labels: :recycle: refactor

#65 ♻️ [Refactor]: 일기 수정 API 수정
  src/main/java/com/beyondB/beyondB/controller/DiaryController.java
  src/main/java/com/beyondB/beyondB/service/impl/DiaryServiceImpl.java
Labels: :recycle: refactor

#69 ♻️ [Feat]: 책 상세 조회 API,반환하는 값들 추가
  src/main/java/com/beyondB/beyondB/BeyondBApplication.java
  src/main/java/com/beyondB/beyondB/converter/BookConverter.java
  src/main/java/com/beyondB/beyondB/dto/request/BookRequestDTO.java
  src/main/java/com/beyondB/beyondB/dto/response/BookResponseDTO.java
  src/main/java/com/beyondB/beyondB/entity/Book.java
  src/main/java/com/beyondB/beyondB/entity/mapping/UserBook.java
  src/main/java/com/beyondB/beyondB/service/impl/BookServiceImpl.java
Labels: :recycle: refactor

#71 ♻️ [Refactor]: 기분별 책 조회 응답 수정
  src/main/java/com/beyondB/beyondB/converter/BookConverter.java
  src/main/java/com/beyondB/beyondB/dto/response/BookResponseDTO.java
Labels: :recycle: refactor

#73 :recycle: [Refactor]: 책 작성 요청 오타 수정
  src/main/java/com/beyondB/beyondB/dto/request/BookRequestDTO.java
  src/main/java/com/beyondB/beyondB/service/impl/BookServiceImpl.java
Labels: :recycle: refactor

#75 🚑 [!HOTFIX]: 나이 수정에 트랜잭션 적용
  src/main/java/com/beyondB/beyondB/service/impl/UserServiceImpl.java
Labels: :bug: bug
